# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1
CPPSRCS += fallible.cpp
MOZBUILD_CXXFLAGS += -Wshadow
LIBRARY_NAME := fallible
FORCE_STATIC_LIB := 1
REAL_LIBRARY := libfallible.a
