# THIS FILE WAS AUTOMATICALLY GENERATED. DO NOT EDIT.

DEFINES += -DNDEBUG=1 -DTRIMMED=1 -DIMPL_MFBT
CPPSRCS += TimeStamp.cpp
CPPSRCS += TimeStamp_darwin.cpp
MOZBUILD_CXXFLAGS += -Wshadow
LIBRARY_NAME := mozglue_misc
FORCE_STATIC_LIB := 1
REAL_LIBRARY := libmozglue_misc.a
